# Bu GitHub Actions iş akışı, cizgivedizi.com scraper betiğini çalıştırır
# ve sonuçları (output klasörünü) doğrudan repository'e commit'ler.

name: çigidizi
on:
  # Zamanlanmış görev: Her 6 saatte bir çalışır
  schedule:
    - cron: '0 */6 * * *'
  
  # Manuel olarak tetiklemeye izin verir
  workflow_dispatch:

# İş akışının sahip olacağı izinleri tanımlar.
# contents: write -> Repository'e commit yapabilmek için gereklidir.
permissions:
  contents: write

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest

    steps:
      # 1. Adım: Repository'deki kodu sanal makineye kopyalar
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Adım: Python 3.11 ortamını kurar
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Adım: Gerekli Python kütüphanelerini yükler
      - name: Install dependencies
        run: pip install requests beautifulsoup4

      # 4. Adım: Scraper betiğini çalıştırır (M3U dosyalarıyla birlikte)
      # Python dosya adınızın 'cizgivedizi_final.py' olduğundan emin olun
      - name: Run the scraper script
        run: python cizgivedizi_final.py dump-all --m3u

      # 5. Adım: Değişiklikleri (yeni/güncellenmiş output klasörünü) commit'ler ve push'lar
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Commit mesajı. Örneğin: "Veri Güncellemesi: 11 Eylül 2025"
          commit_message: "Veri Güncellemesi: $(date +'%d %B %Y')"
          # Commit'i yapacak kullanıcının adı
          commit_user_name: "GitHub Actions Bot"
          # Commit'i yapacak kullanıcının e-postası
          commit_user_email: "actions@github.com"
          # Sadece 'output' klasöründeki değişiklikleri ekle
          file_pattern: "output/*"