# İş akışının adı
name: M3U Playlist Otomatik Güncelleyici

# Bu iş akışının ne zaman çalışacağını belirleyen tetikleyiciler
on:
  # Belirli aralıklarla otomatik olarak çalıştırır (bu örnekte her 6 saatte bir)
  # Cron zamanlayıcısını https://crontab.guru/ adresinden ayarlayabilirsiniz.
  schedule:
    - cron: '0 */6 * * *'
  
  # GitHub arayüzünden manuel olarak çalıştırma imkanı sunar
  workflow_dispatch:

# İş akışında çalıştırılacak işler
jobs:
  update-playlist:
    # İşin çalışacağı sanal makine ortamı
    runs-on: ubuntu-latest

    # Bu iş akışının depoya yazma izni olması için gerekli ayar
    permissions:
      contents: write

    # İşin adımları
    steps:
      # 1. Adım: Depo kodunu sanal makineye indirir
      # Bu, betiğimize ve mevcut M3U dosyamıza erişmemizi sağlar.
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      # 2. Adım: Python ortamını kurar
      - name: Python 3.9 Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      # 3. Adım: Python betiğinin ihtiyaç duyduğu kütüphaneleri yükler
      - name: Gerekli Kütüphaneleri Yükle
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 4. Adım: M3U birleştirme betiğini çalıştırır
      - name: M3U Birleştirme Betiğini Çalıştır
        run: python merge_m3u.py

      # 5. Adım: Değişiklikleri depoya kaydeder ve gönderir
      - name: Değişiklikleri Commit'le ve Push'la
        run: |
          # Git için kullanıcı adı ve e-posta ayarla
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Değişiklik olup olmadığını kontrol et
          # "git status --porcelain" komutu, değişiklik varsa çıktı verir, yoksa boş döner.
          if [[ -n $(git status --porcelain) ]]; then
            echo "Değişiklikler tespit edildi. Commit atılıyor..."
            git add .
            git commit -m "Playlist otomatik olarak güncellendi - $(date)"
            git push
          else
            echo "Değişiklik bulunamadı. Commit atılmıyor."
          fi