# İş akışının adı
name: Film Scraper

# Bu iş akışının ne zaman çalışacağını belirler
on:
  # Her gün gece yarısı (UTC) otomatik olarak çalışmasını sağlar
  schedule:
    - cron: '0 0 * * *'
  # İsterseniz manuel olarak da tetikleyebilmenizi sağlar
  workflow_dispatch:

jobs:
  # "scrape" adında bir görev tanımlıyoruz
  scrape:
    # Görevin çalışacağı sanal makineyi belirtir (Ubuntu'nun son sürümü)
    runs-on: ubuntu-latest

    steps:
      # 1. Adım: Proje dosyalarını sanal makineye kopyalar
      - name: Check out repository code
        uses: actions/checkout@v4

      # 2. Adım: Python'u kurar (örneğin 3.11 sürümü)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Adım: Gerekli Python kütüphanelerini yükler
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 playwright

      # 4. Adım: Playwright için gerekli tarayıcıları yükler
      - name: Install Playwright browsers
        run: python -m playwright install

      # 5. Adım: Asıl Python script'ini çalıştırır
      # Script'inizin adının "a.py" olduğunu varsayıyoruz. 
      # Eğer farklıysa (örneğin "a.py"), burayı güncelleyin.
      - name: Run the scraper script
        run: python a.py