Name: Run Movie Scraper

on:
  workflow_dispatch:   # Manuel çalıştırma için

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 playwright
          playwright install --with-deps chromium

      - name: Run scraper
        run: |
          python a.py

      - name: Commit results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add xtream/imdb_vod.json
          git commit -m "Update IMDb cache [skip ci]" || echo "No changes to commit"
          git push